### ISSUE TITLE
Support Alerting

### ISSUE THREAD

**Issue by lied** [foursquare/datasource-plugin-clouderamanager#5]
If possible provide Alerting support for this plugin. This would make our life here much simpler. If I can support, let me know how.

![image](https://cloud.githubusercontent.com/assets/556083/24903135/cf860f1e-1eac-11e7-918e-ccb97bcced6d.png)

**Comment by tdyas** [comment]
It is unlikely that we will ever have the time to add alerting support for this plugin. Alerting support has to be added to the Grafana backend server because the golang-based backend does not currently make use of the Javascript datasource code to call the datasources to retrieve metrics for alerting purposes.

See https://github.com/grafana/grafana/tree/master/pkg/tsdb for the in-server implementations of various datasources. You'll note that much of that code duplicates the Javascript datasource code.
